[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301
  force = true

[[headers]]
  for = "/admin*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive"

[[headers]]
  for = "/proplayers.html"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive"

[[headers]]
  for = "/visit-stats.html"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive"

[[headers]]
  for = "/images.html"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive"

[[headers]]
  for = "/favicon-preview.html"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive"

[[headers]]
  for = "/mobile-app-mockup*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive"
